// 서강대학교 가상융합전문대학원(GSM) 멤버 디렉토리 데이터 (실제 9기 35인 및 최고 관리자 데이터)
export const INITIAL_MEMBERS = [
  {
    id: "member_v2026101",
    studentId: "v2026101",
    phoneLast4: "6970",
    name: "송민재",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 석사과정 원우",
    avatarColor: "#B60005",
    snsLinks: [{ type: "email", value: "zetekizer1@gmail.com" }],
    tags: ["가상융합비즈니스전공", "석사"],
    bio: "안녕하세요, 송민재입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026102",
    studentId: "v2026102",
    phoneLast4: "3420",
    name: "안지홍",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 석사과정 원우",
    avatarColor: "#2b6cb0",
    snsLinks: [{ type: "email", value: "chloeahn2@gmail.com" }],
    tags: ["가상융합비즈니스전공", "석사"],
    bio: "안녕하세요, 안지홍입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026103",
    studentId: "v2026103",
    phoneLast4: "3790",
    name: "김찬삼",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 석사과정 원우",
    avatarColor: "#319795",
    snsLinks: [{ type: "email", value: "inus_7373@naver.com" }],
    tags: ["가상융합콘텐츠전공", "석사"],
    bio: "안녕하세요, 김찬삼입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026104",
    studentId: "v2026104",
    phoneLast4: "5576",
    name: "박성혜",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 석사과정 원우",
    avatarColor: "#805ad5",
    snsLinks: [{ type: "email", value: "parksunhae112@gmail.com" }],
    tags: ["가상융합콘텐츠전공", "석사"],
    bio: "안녕하세요, 박성혜입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026105",
    studentId: "v2026105",
    phoneLast4: "1182",
    name: "박종현",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 석사과정 원우",
    avatarColor: "#d69e2e",
    snsLinks: [{ type: "email", value: "jjongtephen@gmail.com" }],
    tags: ["가상융합콘텐츠전공", "석사"],
    bio: "안녕하세요, 박종현입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026106",
    studentId: "v2026106",
    phoneLast4: "5662",
    name: "손순혁",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 석사과정 원우",
    avatarColor: "#38a169",
    snsLinks: [{ type: "email", value: "thswnsgur117@naver.com" }],
    tags: ["가상융합콘텐츠전공", "석사"],
    bio: "안녕하세요, 손순혁입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026107",
    studentId: "v2026107",
    phoneLast4: "1555",
    name: "강인",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#dd6b20",
    snsLinks: [{ type: "email", value: "kangin3778@gmail.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 강인입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026108",
    studentId: "v2026108",
    phoneLast4: "0049",
    name: "김영광",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#4a5568",
    snsLinks: [{ type: "email", value: "xhtdrladudr@naver.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 김영광입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026109",
    studentId: "v2026109",
    phoneLast4: "2168",
    name: "김정호",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#5a67d8",
    snsLinks: [{ type: "email", value: "kuh901@gmail.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 김정호입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026110",
    studentId: "v2026110",
    phoneLast4: "0751",
    name: "배준호",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#B60005",
    snsLinks: [{ type: "email", value: "bjh6444@naver.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 배준호입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026111",
    studentId: "v2026111",
    phoneLast4: "8047",
    name: "신현주",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#2b6cb0",
    snsLinks: [{ type: "email", value: "hjs980430@naver.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 신현주입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026112",
    studentId: "v2026112",
    phoneLast4: "5148",
    name: "오수한",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 석사과정 원우",
    avatarColor: "#319795",
    snsLinks: [{ type: "email", value: "dhtmgks2@naver.com" }],
    tags: ["가상융합테크놀로지전공", "석사"],
    bio: "안녕하세요, 오수한입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026113",
    studentId: "v2026113",
    phoneLast4: "3256",
    name: "황민우",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#805ad5",
    snsLinks: [{ type: "email", value: "hmh7735@naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 황민우입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026114",
    studentId: "v2026114",
    phoneLast4: "9302",
    name: "박정근",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#d69e2e",
    snsLinks: [{ type: "email", value: "megnemrudrms@Naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 박정근입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026115",
    studentId: "v2026115",
    phoneLast4: "9530",
    name: "신은정",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#38a169",
    snsLinks: [{ type: "email", value: "younjung3452@naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 신은정입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026116",
    studentId: "v2026116",
    phoneLast4: "9369",
    name: "오원택",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#dd6b20",
    snsLinks: [{ type: "email", value: "soulfiller@gmail.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 오원택입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026117",
    studentId: "v2026117",
    phoneLast4: "5628",
    name: "이주영",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#4a5568",
    snsLinks: [{ type: "email", value: "seolim0210@naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 이주영입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026118",
    studentId: "v2026118",
    phoneLast4: "0095",
    name: "이주영",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#5a67d8",
    snsLinks: [{ type: "email", value: "lkm20022@naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 이주영입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026119",
    studentId: "v2026119",
    phoneLast4: "0345",
    name: "홍지연",
    classYear: "가상융합전문대학원",
    generation: 9,
    headline: "가상융합전문대학원 석사과정 원우",
    avatarColor: "#B60005",
    snsLinks: [{ type: "email", value: "jiyeon4646@naver.com" }],
    tags: ["가상융합전문대학원", "석사"],
    bio: "안녕하세요, 홍지연입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026601",
    studentId: "v2026601",
    phoneLast4: "0453",
    name: "김종성",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#2b6cb0",
    snsLinks: [{ type: "email", value: "kjs781010@gmail.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 김종성입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026602",
    studentId: "v2026602",
    phoneLast4: "1526",
    name: "김창훈",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#319795",
    snsLinks: [{ type: "email", value: "lasswell@naver.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 김창훈입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026603",
    studentId: "v2026603",
    phoneLast4: "0033",
    name: "이창원",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#805ad5",
    snsLinks: [{ type: "email", value: "jiw845838@gmail.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 이창원입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026604",
    studentId: "v2026604",
    phoneLast4: "0876",
    name: "조성원",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#d69e2e",
    snsLinks: [{ type: "email", value: "cbjoe@naver.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 조성원입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026605",
    studentId: "v2026605",
    phoneLast4: "9930",
    name: "조정은",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#38a169",
    snsLinks: [{ type: "email", value: "lawjo@gmail.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 조정은입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026606",
    studentId: "v2026606",
    phoneLast4: "6022",
    name: "한민우",
    classYear: "가상융합비즈니스전공",
    generation: 9,
    headline: "가상융합비즈니스전공 박사과정 원우",
    avatarColor: "#dd6b20",
    snsLinks: [{ type: "email", value: "roland602@naver.com" }],
    tags: ["가상융합비즈니스전공", "박사"],
    bio: "안녕하세요, 한민우입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026607",
    studentId: "v2026607",
    phoneLast4: "1430",
    name: "고한원",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 박사과정 원우",
    avatarColor: "#4a5568",
    snsLinks: [{ type: "email", value: "chamack@naver.com" }],
    tags: ["가상융합콘텐츠전공", "박사"],
    bio: "안녕하세요, 고한원입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026608",
    studentId: "v2026608",
    phoneLast4: "0967",
    name: "김서영",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 박사과정 원우",
    avatarColor: "#5a67d8",
    snsLinks: [{ type: "email", value: "kirasinya00@naver.com" }],
    tags: ["가상융합콘텐츠전공", "박사"],
    bio: "안녕하세요, 김서영입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026609",
    studentId: "v2026609",
    phoneLast4: "1840",
    name: "김하영",
    classYear: "가상융합콘텐츠전공",
    generation: 9,
    headline: "가상융합콘텐츠전공 박사과정 원우",
    avatarColor: "#B60005",
    snsLinks: [{ type: "email", value: "taewoosun@gmail.com" }],
    tags: ["가상융합콘텐츠전공", "박사"],
    bio: "안녕하세요, 김하영입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026610",
    studentId: "v2026610",
    phoneLast4: "6765",
    name: "권혁준",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#2b6cb0",
    snsLinks: [{ type: "email", value: "visualj0@nate.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 권혁준입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026611",
    studentId: "v2026611",
    phoneLast4: "2265",
    name: "금경준",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#319795",
    snsLinks: [{ type: "email", value: "mirme16@naver.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 금경준입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026612",
    studentId: "v2026612",
    phoneLast4: "8875",
    name: "박광석",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#805ad5",
    snsLinks: [{ type: "email", value: "teripak2@nate.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 박광석입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026613",
    studentId: "v2026613",
    phoneLast4: "3837",
    name: "박승현",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#d69e2e",
    snsLinks: [{ type: "email", value: "ppillip@gmail.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 박승현입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026615",
    studentId: "v2026615",
    phoneLast4: "1329",
    name: "신승용",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#38a169",
    snsLinks: [{ type: "email", value: "ssyplot@gmail.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 신승용입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026616",
    studentId: "v2026616",
    phoneLast4: "6907",
    name: "안규원",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#dd6b20",
    snsLinks: [{ type: "email", value: "spider504@naver.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 안규원입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  {
    id: "member_v2026617",
    studentId: "v2026617",
    phoneLast4: "7864",
    name: "장호영",
    classYear: "가상융합테크놀로지전공",
    generation: 9,
    headline: "가상융합테크놀로지전공 박사과정 원우",
    avatarColor: "#4a5568",
    snsLinks: [{ type: "email", value: "semitec99@naver.com" }],
    tags: ["가상융합테크놀로지전공", "박사"],
    bio: "안녕하세요, 장호영입니다. 반갑습니다!",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "박사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "member"
  },
  // 최고 관리자 계정
  {
    id: "admin",
    studentId: "admin",
    phoneLast4: "sogang_gsvc_admin2026!",
    name: "시스템 관리자",
    classYear: "디렉토리 관리",
    generation: null,
    headline: "서강대 가상융합전문대학원(GSVC) 멤버 디렉토리 최고 관리자",
    avatarColor: "#111111",
    snsLinks: [{ type: "email", value: "admin@sogang.ac.kr" }],
    tags: ["관리자", "시스템"],
    bio: "서강대 가상융합전문대학원(GSVC) 디렉토리의 모든 회원 정보와 건의사항을 관리하는 최고 권한 계정입니다.",
    projects: "",
    customContent: "",
    avatarImage: null,
    degreeProcess: "석사",
    academicStatus: "재학",
    education: "",
    experience: "",
    role: "super_admin"
  }
];

export const INITIAL_GUESTBOOK = [];
